version: '3'
services:
  nginx:
    container_name: client_nginx
    image: docker.arvancloud.ir/nginx
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html/
    restart: always
