export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const UPDATE_DASHBOARD_IMAGE = "UPDATE_DASHBOARD_IMAGE";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const STORE_ADMIN_PHONENUMBER = "STORE_ADMIN_PHONENUMBER";

export const USER_SIGNOUT = "USER_SIGNOUT";
