export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const REQUEST_UPGRADE_FAVORITES = "REQUEST_UPGRADE_FAVORITES";
export const UPGRADE_FAVORITES = "UPGRADE_FAVORITES";
export const ERROR_UPGRADE_FAVORITES = "ERROR_UPGRADE_FAVORITES";
export const DELETE_DEPRECATED_FAVORITES_ITEM =
  "DELETE_DEPRECATED_FAVORITES_ITEM";
