export const SAVE_SHOP_PRODUCTS = "SAVE_SHOP_PRODUCTS";
export const CLEAR_SHOP_PRODUCTS = "CLEAR_SHOP_PRODUCTS";
export const SET_ALL_BRANDS = "SET_ALL_BRANDS";
export const UPDATE_ALL_BRANDS = "UPDATE_ALL_BRANDS";
export const CLEAR_ALL_BRANDS = "CLEAR_ALL_BRANDS";
export const CLEAR_ITEMS = "CLEAR_ITEMS";
export const PUSH_OLD_ITEMS = "PUSH_OLD_ITEMS";

