export const SAVE_SUPPLIER_PRODUCTS = "SAVE_SUPPLIER_PRODUCTS";
export const CLEAR_SUPPLIER_PRODUCTS = "CLEAR_SUPPLIER_PRODUCTS";
export const CLEAR_SUPPLIER_ACTIVE_PRODUCTS = "CLEAR_SUPPLIER_ACTIVE_PRODUCTS";

